### ISSUE TITLE
Grouping / TreeGrid question

### ISSUE THREAD

**Issue by akchamczuk** [mgallegos/laravel-jqgrid#31]
Hi There - so far I love the product, but I was wondering if 'Grouping' will be added to your ToDo list (or how soon or how soon TreeGrid might be added.  Love to hear if anybody has an easy workaround.  Thanks

**Comment by mgallegos** [comment]
Hello, Grouping and TreeGrid are already implemented but not yet documented.

In order to have this funcionality, install the package like this: "mgallegos/laravel-jqgrid": "dev-master"

The only documentation I can offer your at this moment, is the code of one of my projects.

Here is an example of grouping [it looks like this](https://drive.google.com/file/d/0B0T3kXdFmQIOMjRSajM0em9uT0U/view?usp=sharing):

[View (Lines from 1190 to 1228)](https://github.com/mgallegos/decima-erp/blob/master/workbench/mgallegos/decima-accounting/src/views/journal-management.blade.php
)

Here is an example of treegrid [it looks like this](https://drive.google.com/file/d/0B0T3kXdFmQIOYUJvMHJCb3NZSVU/view?usp=sharing):

- [View (Lines from 367 to 396)](https://github.com/mgallegos/decima-erp/blob/master/workbench/mgallegos/decima-accounting/src/views/account-management.blade.php)
- [Grid Repository (lines from 50 to 54)](https://github.com/mgallegos/decima-erp/blob/master/workbench/mgallegos/decima-accounting/src/Mgallegos/DecimaAccounting/Accounting/Repositories/Account/EloquentAccountGridRepository.php)

**Comment by akchamczuk** [comment]
Thank-you!

**Comment by mgallegos** [comment]
Sorry, a small correction the key lines in grouping are: 

[View (Lines from 1202 and 1203)](https://github.com/mgallegos/decima-erp/blob/master/workbench/mgallegos/decima-accounting/src/views/journal-management.blade.php#L1202
)

**Comment by KrasilnikovKB** [comment]
:(((

![image](https://cloud.githubusercontent.com/assets/16627494/17202378/99f9aea8-54a1-11e6-910f-9a097b16265d.png)
