### ISSUE TITLE
hasMany relationship squeezed into 1 cell, editable & searchable

### ISSUE THREAD

**Issue by 0x42h** [mgallegos/laravel-jqgrid#42]
Hi there,

Great work. Looks really good all this. However, I have an exotic requirement which is, I believe, all-encompassingly described in the subject. I need to display a hasMany relationship in one of the cells of each object row, which should become editable and searchable. I have come a long way, so here are the facts and the lacks:

My routes.php (fairly unchanged from the tutorial you made)

``` php
Route::post('/companies-grid', function () {
    GridEncoder::encodeRequestedData(new CompanyRepository(new Company()), Input::all());
}); 
```

My companyRepository:

``` php
    public function __construct(Model $Model)
    {
      $this->Database = $Model::with('Nace11s');

      $this->visibleColumns = $Model->getAttributes();

      $this->orderBy = array(array('name', 'asc'));
    }        
```

So with this, I get my objects through in the grid and with a formatter in javascript I can display a comma-separated list of the properties of the object. Now I have also implemented a multiselect to filter this column in the grid with multiple values, which, of course, returns me a server error, because (in my case) sql server cannot find the column "nace11s", of course, because it does not exist. The input parameters come through correctly though, when I, for instance, select 11,12,13,14, it passes those values in a comma-separated list to the filter parameters in the post request. Now of course the GridEncoder doesn't know how to go about this and dies on a sql error produced by the sql generated by the EloquentRepositoryAbstract (I suppose?). As I am all new to your interface, maybe you could point me out to the right places for the right approach on handling this.

**Comment by mgallegos** [comment]
Hello, I hope this helps:

- Why don't you use Query Builder instead of your Eloquent Model in your repository class ([as shown in step 2 in the documentation](http://www.mariogallegos.com/open-source-development/laravel-jqgrid/getting-started)), that way you make sure that the column "nace11s" exists.
- And if you want to do something different to filter an specific column, take a look at the code of the class [EloquentRepositoryAbstract](https://github.com/mgallegos/laravel-jqgrid/blob/master/src/Mgallegos/LaravelJqgrid/Repositories/EloquentRepositoryAbstract.php) this is the class that your "Repository class" is extending, you could overwrite any of its method if you want.
